// Agent
export enum AgentTypeEnum {
  CAR_TOWING = "CAR_TOWING",
  DELIVERY = "DELIVERY",
}

export enum AgentStatusEnum {
  OFFLINE = "OFFLINE",
  ONLINE = "ONLINE",
}

export enum AgentRegistrationDocumentEnum {
  ABN = "ABN",
  DRIVER_LICENSE = "DRIVER_LICENSE",
  INSURANCE = "INSURANCE",
  OTHER = "OTHER",
  PROFILE_PHOTO = "PROFILE_PHOTO",
  VEHICLE_REGISTRATION = "VEHICLE_REGISTRATION",
}

export enum ApprovalStatusEnum {
  PENDING = "PENDING",
  REJECTED = "REJECTED",
  APPROVED = "APPROVED",
}

// Order
export enum OrderStatusEnum {
  PENDING = 'PENDING',
  DELIVERY_PAID = 'DELIVERY_PAID',
  AGENT_ASSIGNED = 'AGENT_ASSIGNED',
  AGENT_REACHED_STORE = 'AGENT_REACHED_STORE',
  ITEMS_PAYMENT_RECEIVED = 'ITEMS_PAYMENT_RECEIVED',
  OUT_FOR_DELIVERY = 'OUT_FOR_DELIVERY',
  DELIVERED = 'DELIVERED',
  COMPLETED = 'COMPLETED',
  CANCELED = 'CANCELED',
  FAILED = 'FAILED',
}

export enum OrderTypeEnum {
  DELIVERY = "DELIVERY",
  PICKUP = "PICKUP",
}

// User
export enum UserRoleEnum {
  ADMIN = "ADMIN",
  AGENT = "AGENT",
  CUSTOMER = "CUSTOMER",
  SUPPORT = "SUPPORT",
}

//Payment
export enum PaymentStatusEnum {
  NOT_PAID = 'NOT_PAID',
  PAID = 'PAID',
  ERROR = 'ERROR',
  REFUNDED = 'REFUNDED',
}

//Item
export enum ItemStatusEnum {
  PROPOSED = 'PROPOSED',
  PENDING_VERIFICATION = 'PENDING_VERIFICATION',
  CONFIRMED = 'CONFIRMED',
  REJECTED = 'REJECTED',
}